USE jugos_ventas;

SELECT * FROM tabla_de_productos;

SELECT NOMBRE_DEL_PRODUCTO, PRECIO_DE_LISTA,
CASE
	 WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
     WHEN PRECIO_DE_LISTA BETWEEN 5 AND 12 THEN 'ASEQUIBLE'
     ELSE 'BARATO'
END AS PRECIO     
FROM tabla_de_productos;

SELECT ENVASE, SABOR,
CASE
	 WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
     WHEN PRECIO_DE_LISTA BETWEEN 5 AND 12 THEN 'ASEQUIBLE'
     ELSE 'BARATO'
END AS PRECIO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO 
FROM tabla_de_productos WHERE TAMANO = '700 ML' GROUP BY 
CASE
	 WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
     WHEN PRECIO_DE_LISTA BETWEEN 5 AND 12 THEN 'ASEQUIBLE'
     ELSE 'BARATO'
END
ORDER BY ENVASE;


