USE jugos_ventas;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes WHERE LIMITE_TOTAL > 300000 GROUP BY ESTADO; #ERROR

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO HAVING LIMITE_TOTAL > 300000;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MÁXIMO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO FROM tabla_de_productos GROUP BY ENVASE;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MÁXIMO, MIN(PRECIO_DE_LISTA)
AS PRECIO_MINIMO, SUM(PRECIO_DE_LISTA) AS SUMA_PRECIO
FROM tabla_de_productos GROUP BY ENVASE HAVING SUMA_PRECIO > 80;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MÁXIMO, MIN(PRECIO_DE_LISTA)
AS PRECIO_MINIMO, SUM(PRECIO_DE_LISTA) AS SUMA_PRECIO
FROM tabla_de_productos GROUP BY ENVASE HAVING SUMA_PRECIO > 80 AND PRECIO_MÁXIMO >= 5;


