SELECT LTRIM("   MYSQL ES FÁCIL");
SELECT RTRIM("MYSQL ES FÁCIL   ");

SELECT TRIM("   MYSQL ES FÁCIL   ");

SELECT CONCAT("MYSQL ES FÁCIL", ", O NO?");

SELECT UPPER("MYSQL ES UNA DB INTERESANTE");

SELECT LOWER("MYSQL ES UNA DB INTERESANTE");

SELECT SUBSTRING("mysql es una db interesante", 14,4);

SELECT CONCAT(NOMBRE, " ", DNI) FROM tabla_de_clientes;
