#CANTIDAD VENDIDA POR SABOR EN EL AÑO 2016
SELECT P.SABOR, SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA) ORDER BY SUM(IFA.CANTIDAD) DESC;

# CANTIDAD DE PRODUCTO VENDIDO EN EL AÑO 2016
SELECT SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA) ORDER BY SUM(IFA.CANTIDAD) DESC;

SELECT * FROM (
SELECT P.SABOR, SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA) ORDER BY SUM(IFA.CANTIDAD) DESC
) VENTAS_SABOR
INNER JOIN (
SELECT SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)
) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO;

SELECT VENTAS_SABOR.SABOR, VENTAS_SABOR.AÑO, VENTAS_SABOR.CANTIDAD_TOTAL, 
ROUND((VENTAS_SABOR.CANTIDAD_TOTAL/VENTA_TOTAL.CANTIDAD_TOTAL)*100,2) AS PORCENTAJE_DE_VENTA FROM (
SELECT P.SABOR, SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA) ORDER BY SUM(IFA.CANTIDAD) DESC
) VENTAS_SABOR
INNER JOIN (
SELECT SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)
) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO
ORDER BY VENTAS_SABOR.CANTIDAD_TOTAL DESC;