SELECT * FROM facturas;

SELECT * FROM items_facturas;

SELECT F.DNI, F.FECHA_VENTA, IFA.CANTIDAD
FROM facturas F INNER JOIN items_facturas IFA
ON F.NUMERO = IFA.NUMERO;

SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, IFA.CANTIDAD
FROM facturas F INNER JOIN items_facturas IFA
ON F.NUMERO = IFA.NUMERO;

# CANTIDAD DE VENTAS POR MES PARA CADA CLIENTE
SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO,
SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA
FROM facturas F INNER JOIN items_facturas IFA
ON F.NUMERO = IFA.NUMERO
GROUP BY F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y');

# LÍMITE DE VENTAS PARA CADA CLIENTE (VOLUMEN EN DECILITROS)
SELECT * FROM tabla_de_clientes TC;

SELECT DNI, TC.NOMBRE, VOLUMEN_DE_COMPRA FROM tabla_de_clientes TC; 

SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO,
SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM facturas F INNER JOIN items_facturas IFA
ON F.NUMERO = IFA.NUMERO
INNER JOIN tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y');

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) AS DIFERENCIA,
CASE
	WHEN (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'VÁLIDA'
    ELSE 'INVÁLIDA'
END AS STATUS_VENTA
FROM (
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO,
SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM facturas F INNER JOIN items_facturas IFA
ON F.NUMERO = IFA.NUMERO
INNER JOIN tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y')) A; 
